### ISSUE TITLE
`utf32` moved to LegacyStrings

### ISSUE THREAD

**Issue by timholy** [Keno/Gallium.jl#134] opened 2016-07-16 12:36 UTC
```jl
julia> using Gallium
INFO: Precompiling module Gallium...
ERROR: LoadError: `utf32` has been moved to the package LegacyStrings.jl:
Run Pkg.add("LegacyStrings") to install LegacyStrings on Julia v0.5-;
...
```

**Comment by josefsachsconning** [comment] 2016-07-16 12:46
Duplicate of #133?  In other words, already fixed in master?

**Closed** 2016-07-16 22:40 UTC
